### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by MLopezJ** [MLopezJ/asset-tracker-cloud-coiote-azure-converter-js#29]
After review of code with Pisut and Markus, this is the feedback received.

- [x] dependencies are not up to date
- [x] add ADR: we use intermediate format (nRF Asset Tracker LwM2M), because we expect other LwM2M integrations to appear in the future
- [x] use https://www.npmjs.com/package/@nordicsemiconductor/asset-tracker-cloud-docs
- [x] do not use index.js https://stackoverflow.com/questions/22512992/how-to-use-the-main-parameter-in-package-json
- [x] test coverage: npx jest --coverage does not work
- [x] add better name: https://github.com/MLopezJ/asset-tracker-cloud-coiote-azure-converter-js/blob/15c5c9fe45642dcd9e41363e15f674bc7aa863e1/src/index.ts#L23 
- [x] instead of treating LwM2M registry objects and custom objects seperately, at the very beginning pick all allowed registry and custom objects into on "nRF Asset Tracker LwM2M Registry" and use that
- [x] remove hardcoded magic number 1563968743666, use Azure IoT Hub Metadata timestamp for the respective property. individual timestamp instead of global timestamp
- [x] asset tracker azure types should be included from the module https://www.npmjs.com/package/@nordicsemiconductor/asset-tracker-cloud-docs
- [x] use of `any` is forbidden
- [x]  if importing lodash modules use the function name, not `_.<functionName>`. check option to use reduce and not map
- [ ] question to azure: do all Azure $metadata timestamps get update when one object is changed? So we can more precisely determine update time of a single object.
- [x] implement custom metadata timestamp as server time for each object
- [x] rename "create..." functions/files  to "convert/name"
- [x] GitHub Actions should execute the example (and it should work)
- [x] asset-tracker-cloud-coiote-azure-converter-js/src/index.ts at 15c5c9fe45642dcd9e41363e15f674bc7aa863e1 · MLopezJ/asset-tracker-cloud-coiote-azure-converter-js
- [x] Build expected input of Asset Tracker from the result of the integration between Coiote and Azure - MLopezJ/asset-tracker-cloud-coiote-azure-converter-js
- [x] Node.js version 20 (also in GitHub runners)
- [x] check `beforeEach` in tests
- [x] add metadata timestamp as example in readme
- [ ] check TODOs

** Would be nice to add coverage badge

**Comment by MLopezJ** [comment]
## TODO

- [ ] Update dependencies automatically

**Comment by MLopezJ** [comment]
- [ ] Use tag tree instead of saga here https://github.com/MLopezJ/asset-tracker-cloud-coiote-azure-converter-js/blob/saga/documents/environment.md  .  https://github.com/NordicSemiconductor/asset-tracker-cloud-docs/tree/v29.0.2/docs
- [ ] Link is broken in example https://github.com/MLopezJ/asset-tracker-cloud-coiote-azure-converter-js/blob/saga/src/transform.spec.ts
- [x] https://github.com/MLopezJ/asset-tracker-cloud-coiote-azure-converter-js#missing-values add what is default value for missing values
- [x] Add Transformation steps to ADR https://github.com/MLopezJ/asset-tracker-cloud-coiote-azure-converter-js#transformation-steps
- [x] Required objects table should stay in readme https://github.com/MLopezJ/asset-tracker-cloud-coiote-azure-converter-js#1--pick-required-objects
- [x] ADR example https://github.com/hello-nrfcloud/backend/tree/saga/adr
